title: Silverashの隙间 
baseurl: ""
url: "https://siiverash.github.io"
repository: "siiverash/siiverash.github.io"
description: "Attention Is All You Need!"

# 显式提供元数据，避免插件去调 GitHub API
github: [metadata]
  name: "siiverash.github.io"
  owner: "siiverash"
  is_project: false

social:
  github: "https://github.com/siiverash"
  twitter: "https://x.com/Wolfram1907" 
  pixiv: "https://www.pixiv.net/users/55937658" 
  email: "z1379523665@gmail.com" 

plugins:
  - jekyll-feed
