title: Silverashの隙间
timezone: Asia/Shanghai
baseurl: "" # 确保为空，适应顶级域名
url: "" # 动态适应
repository: "siiverash/siiverash.github.io"
description: "Attention Is All You Need!"
encoding: utf-8 # 显式指定 UTF-8 编码

# 显式提供元数据，避免插件去调 GitHub API
# 注意：格式必须严格遵守 YAML 缩进
github:
  name: "siiverash.github.io"
  owner: "siiverash"
  is_project: false

social:
  github: "https://github.com/siiverash"
  twitter: "https://x.com/Wolfram1907" 
  pixiv: "https://www.pixiv.net/users/55937658" 
  email: "z1379523665@gmail.com" 

plugins:
  - jekyll-feed
