title: Silverashの隙间 
baseurl: ""
url: "https://siiverash.github.io"

# 社交链接配置
social:
  github: "https://github.com/siiverash"
  twitter: "https://x.com/Wolfram1907" 
  pixiv: "https://www.pixiv.net/users/55937658" 
  email: "z1379523665@gmail.com" 

# 插件
plugins:
  - jekyll-feed
